version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - service.env
    ports:
      - "8001:8001"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001