[tool.bandit]
exclude_dirs = ["tests"]

[tool.mypy]
check_untyped_defs = "True"
disallow_any_generics = "True"
ignore_missing_imports = "True"
no_implicit_optional = "True"
no_incremental = "True"
pretty = "True"
python_version = "3.12"
show_column_numbers = "True"
warn_return_any = "True"
warn_unused_ignores = "True"

[tool.ruff]
line-length = 120